apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      appname: epam-diploma
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - interval: 15s
    - port: http
    - path: /metrics